/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.LocalDateTime;

import jooq.tables.Account;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> implements Record5<Long, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account.telegram_id</code>.
     */
    public void setTelegramId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.telegram_id</code>.
     */
    public Long getTelegramId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.account.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.account.user_name</code>.
     */
    public void setUserName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account.user_name</code>.
     */
    public String getUserName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.account.birthday</code>.
     */
    public void setBirthday(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account.birthday</code>.
     */
    public LocalDateTime getBirthday() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Account.ACCOUNT.TELEGRAM_ID;
    }

    @Override
    public Field<String> field2() {
        return Account.ACCOUNT.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Account.ACCOUNT.LAST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Account.ACCOUNT.USER_NAME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Account.ACCOUNT.BIRTHDAY;
    }

    @Override
    public Long component1() {
        return getTelegramId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public String component4() {
        return getUserName();
    }

    @Override
    public LocalDateTime component5() {
        return getBirthday();
    }

    @Override
    public Long value1() {
        return getTelegramId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public String value4() {
        return getUserName();
    }

    @Override
    public LocalDateTime value5() {
        return getBirthday();
    }

    @Override
    public AccountRecord value1(Long value) {
        setTelegramId(value);
        return this;
    }

    @Override
    public AccountRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public AccountRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public AccountRecord value4(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public AccountRecord value5(LocalDateTime value) {
        setBirthday(value);
        return this;
    }

    @Override
    public AccountRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Long telegramId, String firstName, String lastName, String userName, LocalDateTime birthday) {
        super(Account.ACCOUNT);

        setTelegramId(telegramId);
        setFirstName(firstName);
        setLastName(lastName);
        setUserName(userName);
        setBirthday(birthday);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(jooq.tables.pojos.Account value) {
        super(Account.ACCOUNT);

        if (value != null) {
            setTelegramId(value.getTelegramId());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setUserName(value.getUserName());
            setBirthday(value.getBirthday());
        }
    }
}
