/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.util.UUID;

import jooq.tables.Media;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MediaRecord extends UpdatableRecordImpl<MediaRecord> implements Record3<UUID, byte[], String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.media.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.media.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.media.media</code>.
     */
    public void setMedia(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.media.media</code>.
     */
    public byte[] getMedia() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>public.media.media_type</code>.
     */
    public void setMediaType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.media.media_type</code>.
     */
    public String getMediaType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, byte[], String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, byte[], String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Media.MEDIA.ID;
    }

    @Override
    public Field<byte[]> field2() {
        return Media.MEDIA.MEDIA_;
    }

    @Override
    public Field<String> field3() {
        return Media.MEDIA.MEDIA_TYPE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public byte[] component2() {
        return getMedia();
    }

    @Override
    public String component3() {
        return getMediaType();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public byte[] value2() {
        return getMedia();
    }

    @Override
    public String value3() {
        return getMediaType();
    }

    @Override
    public MediaRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public MediaRecord value2(byte[] value) {
        setMedia(value);
        return this;
    }

    @Override
    public MediaRecord value3(String value) {
        setMediaType(value);
        return this;
    }

    @Override
    public MediaRecord values(UUID value1, byte[] value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaRecord
     */
    public MediaRecord() {
        super(Media.MEDIA);
    }

    /**
     * Create a detached, initialised MediaRecord
     */
    public MediaRecord(UUID id, byte[] media, String mediaType) {
        super(Media.MEDIA);

        setId(id);
        setMedia(media);
        setMediaType(mediaType);
    }

    /**
     * Create a detached, initialised MediaRecord
     */
    public MediaRecord(jooq.tables.pojos.Media value) {
        super(Media.MEDIA);

        if (value != null) {
            setId(value.getId());
            setMedia(value.getMedia());
            setMediaType(value.getMediaType());
        }
    }
}
