/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Chat;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRecord extends UpdatableRecordImpl<ChatRecord> implements Record6<Long, String, String, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat.chat_id</code>.
     */
    public void setChatId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chat.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chat.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chat.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.chat.chat_type</code>.
     */
    public void setChatType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chat.chat_type</code>.
     */
    public String getChatType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.chat.holiday_notice</code>.
     */
    public void setHolidayNotice(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chat.holiday_notice</code>.
     */
    public Boolean getHolidayNotice() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.chat.birthday_notice</code>.
     */
    public void setBirthdayNotice(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.chat.birthday_notice</code>.
     */
    public Boolean getBirthdayNotice() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.chat.daily_notice</code>.
     */
    public void setDailyNotice(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.chat.daily_notice</code>.
     */
    public Boolean getDailyNotice() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, Boolean, Boolean, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Chat.CHAT.CHAT_ID;
    }

    @Override
    public Field<String> field2() {
        return Chat.CHAT.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Chat.CHAT.CHAT_TYPE;
    }

    @Override
    public Field<Boolean> field4() {
        return Chat.CHAT.HOLIDAY_NOTICE;
    }

    @Override
    public Field<Boolean> field5() {
        return Chat.CHAT.BIRTHDAY_NOTICE;
    }

    @Override
    public Field<Boolean> field6() {
        return Chat.CHAT.DAILY_NOTICE;
    }

    @Override
    public Long component1() {
        return getChatId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getChatType();
    }

    @Override
    public Boolean component4() {
        return getHolidayNotice();
    }

    @Override
    public Boolean component5() {
        return getBirthdayNotice();
    }

    @Override
    public Boolean component6() {
        return getDailyNotice();
    }

    @Override
    public Long value1() {
        return getChatId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getChatType();
    }

    @Override
    public Boolean value4() {
        return getHolidayNotice();
    }

    @Override
    public Boolean value5() {
        return getBirthdayNotice();
    }

    @Override
    public Boolean value6() {
        return getDailyNotice();
    }

    @Override
    public ChatRecord value1(Long value) {
        setChatId(value);
        return this;
    }

    @Override
    public ChatRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ChatRecord value3(String value) {
        setChatType(value);
        return this;
    }

    @Override
    public ChatRecord value4(Boolean value) {
        setHolidayNotice(value);
        return this;
    }

    @Override
    public ChatRecord value5(Boolean value) {
        setBirthdayNotice(value);
        return this;
    }

    @Override
    public ChatRecord value6(Boolean value) {
        setDailyNotice(value);
        return this;
    }

    @Override
    public ChatRecord values(Long value1, String value2, String value3, Boolean value4, Boolean value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatRecord
     */
    public ChatRecord() {
        super(Chat.CHAT);
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    public ChatRecord(Long chatId, String title, String chatType, Boolean holidayNotice, Boolean birthdayNotice, Boolean dailyNotice) {
        super(Chat.CHAT);

        setChatId(chatId);
        setTitle(title);
        setChatType(chatType);
        setHolidayNotice(holidayNotice);
        setBirthdayNotice(birthdayNotice);
        setDailyNotice(dailyNotice);
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    public ChatRecord(db.tables.pojos.Chat value) {
        super(Chat.CHAT);

        if (value != null) {
            setChatId(value.getChatId());
            setTitle(value.getTitle());
            setChatType(value.getChatType());
            setHolidayNotice(value.getHolidayNotice());
            setBirthdayNotice(value.getBirthdayNotice());
            setDailyNotice(value.getDailyNotice());
        }
    }
}
