/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Account;
import jooq.tables.AccountChat;
import jooq.tables.Chat;
import jooq.tables.FlywaySchemaHistory;
import jooq.tables.Media;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.account_chat</code>.
     */
    public static final AccountChat ACCOUNT_CHAT = AccountChat.ACCOUNT_CHAT;

    /**
     * The table <code>public.chat</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.media</code>.
     */
    public static final Media MEDIA = Media.MEDIA;
}
