/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;
import java.util.Optional;

import jooq.tables.AccountChat;
import jooq.tables.records.AccountChatRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AccountChatDao extends DAOImpl<AccountChatRecord, jooq.tables.pojos.AccountChat, Long> {

    /**
     * Create a new AccountChatDao without any configuration
     */
    public AccountChatDao() {
        super(AccountChat.ACCOUNT_CHAT, jooq.tables.pojos.AccountChat.class);
    }

    /**
     * Create a new AccountChatDao with an attached configuration
     */
    @Autowired
    public AccountChatDao(Configuration configuration) {
        super(AccountChat.ACCOUNT_CHAT, jooq.tables.pojos.AccountChat.class, configuration);
    }

    @Override
    public Long getId(jooq.tables.pojos.AccountChat object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.AccountChat> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AccountChat.ACCOUNT_CHAT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.tables.pojos.AccountChat> fetchById(Long... values) {
        return fetch(AccountChat.ACCOUNT_CHAT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.tables.pojos.AccountChat fetchOneById(Long value) {
        return fetchOne(AccountChat.ACCOUNT_CHAT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<jooq.tables.pojos.AccountChat> fetchOptionalById(Long value) {
        return fetchOptional(AccountChat.ACCOUNT_CHAT.ID, value);
    }

    /**
     * Fetch records that have <code>account_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.AccountChat> fetchRangeOfAccountId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AccountChat.ACCOUNT_CHAT.ACCOUNT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>account_id IN (values)</code>
     */
    public List<jooq.tables.pojos.AccountChat> fetchByAccountId(Long... values) {
        return fetch(AccountChat.ACCOUNT_CHAT.ACCOUNT_ID, values);
    }

    /**
     * Fetch records that have <code>chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.AccountChat> fetchRangeOfChatId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(AccountChat.ACCOUNT_CHAT.CHAT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>chat_id IN (values)</code>
     */
    public List<jooq.tables.pojos.AccountChat> fetchByChatId(Long... values) {
        return fetch(AccountChat.ACCOUNT_CHAT.CHAT_ID, values);
    }
}
