/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;
import java.util.Optional;

import jooq.tables.Chat;
import jooq.tables.records.ChatRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ChatDao extends DAOImpl<ChatRecord, jooq.tables.pojos.Chat, Long> {

    /**
     * Create a new ChatDao without any configuration
     */
    public ChatDao() {
        super(Chat.CHAT, jooq.tables.pojos.Chat.class);
    }

    /**
     * Create a new ChatDao with an attached configuration
     */
    @Autowired
    public ChatDao(Configuration configuration) {
        super(Chat.CHAT, jooq.tables.pojos.Chat.class, configuration);
    }

    @Override
    public Long getId(jooq.tables.pojos.Chat object) {
        return object.getChatId();
    }

    /**
     * Fetch records that have <code>chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Chat> fetchRangeOfChatId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Chat.CHAT.CHAT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>chat_id IN (values)</code>
     */
    public List<jooq.tables.pojos.Chat> fetchByChatId(Long... values) {
        return fetch(Chat.CHAT.CHAT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>chat_id = value</code>
     */
    public jooq.tables.pojos.Chat fetchOneByChatId(Long value) {
        return fetchOne(Chat.CHAT.CHAT_ID, value);
    }

    /**
     * Fetch a unique record that has <code>chat_id = value</code>
     */
    public Optional<jooq.tables.pojos.Chat> fetchOptionalByChatId(Long value) {
        return fetchOptional(Chat.CHAT.CHAT_ID, value);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Chat> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Chat.CHAT.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<jooq.tables.pojos.Chat> fetchByTitle(String... values) {
        return fetch(Chat.CHAT.TITLE, values);
    }

    /**
     * Fetch records that have <code>chat_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Chat> fetchRangeOfChatType(String lowerInclusive, String upperInclusive) {
        return fetchRange(Chat.CHAT.CHAT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>chat_type IN (values)</code>
     */
    public List<jooq.tables.pojos.Chat> fetchByChatType(String... values) {
        return fetch(Chat.CHAT.CHAT_TYPE, values);
    }

    /**
     * Fetch records that have <code>holiday_notice BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Chat> fetchRangeOfHolidayNotice(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Chat.CHAT.HOLIDAY_NOTICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>holiday_notice IN (values)</code>
     */
    public List<jooq.tables.pojos.Chat> fetchByHolidayNotice(Boolean... values) {
        return fetch(Chat.CHAT.HOLIDAY_NOTICE, values);
    }

    /**
     * Fetch records that have <code>birthday_notice BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Chat> fetchRangeOfBirthdayNotice(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Chat.CHAT.BIRTHDAY_NOTICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>birthday_notice IN (values)</code>
     */
    public List<jooq.tables.pojos.Chat> fetchByBirthdayNotice(Boolean... values) {
        return fetch(Chat.CHAT.BIRTHDAY_NOTICE, values);
    }

    /**
     * Fetch records that have <code>daily_notice BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Chat> fetchRangeOfDailyNotice(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Chat.CHAT.DAILY_NOTICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>daily_notice IN (values)</code>
     */
    public List<jooq.tables.pojos.Chat> fetchByDailyNotice(Boolean... values) {
        return fetch(Chat.CHAT.DAILY_NOTICE, values);
    }
}
