/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;
import java.util.Optional;

import jooq.tables.ChatDb;
import jooq.tables.records.ChatDbRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ChatDbDao extends DAOImpl<ChatDbRecord, jooq.tables.pojos.ChatDb, Long> {

    /**
     * Create a new ChatDbDao without any configuration
     */
    public ChatDbDao() {
        super(ChatDb.CHAT_DB, jooq.tables.pojos.ChatDb.class);
    }

    /**
     * Create a new ChatDbDao with an attached configuration
     */
    @Autowired
    public ChatDbDao(Configuration configuration) {
        super(ChatDb.CHAT_DB, jooq.tables.pojos.ChatDb.class, configuration);
    }

    @Override
    public Long getId(jooq.tables.pojos.ChatDb object) {
        return object.getChatId();
    }

    /**
     * Fetch records that have <code>chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchRangeOfChatId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ChatDb.CHAT_DB.CHAT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>chat_id IN (values)</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchByChatId(Long... values) {
        return fetch(ChatDb.CHAT_DB.CHAT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>chat_id = value</code>
     */
    public jooq.tables.pojos.ChatDb fetchOneByChatId(Long value) {
        return fetchOne(ChatDb.CHAT_DB.CHAT_ID, value);
    }

    /**
     * Fetch a unique record that has <code>chat_id = value</code>
     */
    public Optional<jooq.tables.pojos.ChatDb> fetchOptionalByChatId(Long value) {
        return fetchOptional(ChatDb.CHAT_DB.CHAT_ID, value);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(ChatDb.CHAT_DB.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchByTitle(String... values) {
        return fetch(ChatDb.CHAT_DB.TITLE, values);
    }

    /**
     * Fetch records that have <code>chat_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchRangeOfChatType(String lowerInclusive, String upperInclusive) {
        return fetchRange(ChatDb.CHAT_DB.CHAT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>chat_type IN (values)</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchByChatType(String... values) {
        return fetch(ChatDb.CHAT_DB.CHAT_TYPE, values);
    }

    /**
     * Fetch records that have <code>holiday_notice BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchRangeOfHolidayNotice(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ChatDb.CHAT_DB.HOLIDAY_NOTICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>holiday_notice IN (values)</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchByHolidayNotice(Boolean... values) {
        return fetch(ChatDb.CHAT_DB.HOLIDAY_NOTICE, values);
    }

    /**
     * Fetch records that have <code>birthday_notice BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchRangeOfBirthdayNotice(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ChatDb.CHAT_DB.BIRTHDAY_NOTICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>birthday_notice IN (values)</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchByBirthdayNotice(Boolean... values) {
        return fetch(ChatDb.CHAT_DB.BIRTHDAY_NOTICE, values);
    }

    /**
     * Fetch records that have <code>daily_notice BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchRangeOfDailyNotice(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ChatDb.CHAT_DB.DAILY_NOTICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>daily_notice IN (values)</code>
     */
    public List<jooq.tables.pojos.ChatDb> fetchByDailyNotice(Boolean... values) {
        return fetch(ChatDb.CHAT_DB.DAILY_NOTICE, values);
    }
}
