/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Account;
import db.tables.AccountChat;
import db.tables.Chat;
import db.tables.FlywaySchemaHistory;
import db.tables.Media;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.account_chat</code>.
     */
    public final AccountChat ACCOUNT_CHAT = AccountChat.ACCOUNT_CHAT;

    /**
     * The table <code>public.chat</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.media</code>.
     */
    public final Media MEDIA = Media.MEDIA;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            AccountChat.ACCOUNT_CHAT,
            Chat.CHAT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Media.MEDIA
        );
    }
}
