/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountChat implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long accountId;
    private Long chatId;

    public AccountChat() {}

    public AccountChat(AccountChat value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.chatId = value.chatId;
    }

    public AccountChat(
        Long id,
        Long accountId,
        Long chatId
    ) {
        this.id = id;
        this.accountId = accountId;
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.account_chat.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.account_chat.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.account_chat.account_id</code>.
     */
    public Long getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>public.account_chat.account_id</code>.
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>public.account_chat.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.account_chat.chat_id</code>.
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountChat (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(chatId);

        sb.append(")");
        return sb.toString();
    }
}
