/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          telegramId;
    private String        firstName;
    private String        lastName;
    private String        userName;
    private LocalDateTime birthday;

    public Account() {}

    public Account(Account value) {
        this.telegramId = value.telegramId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.userName = value.userName;
        this.birthday = value.birthday;
    }

    public Account(
        Long          telegramId,
        String        firstName,
        String        lastName,
        String        userName,
        LocalDateTime birthday
    ) {
        this.telegramId = telegramId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.userName = userName;
        this.birthday = birthday;
    }

    /**
     * Getter for <code>public.account.telegram_id</code>.
     */
    public Long getTelegramId() {
        return this.telegramId;
    }

    /**
     * Setter for <code>public.account.telegram_id</code>.
     */
    public void setTelegramId(Long telegramId) {
        this.telegramId = telegramId;
    }

    /**
     * Getter for <code>public.account.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.account.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>public.account.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.account.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>public.account.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>public.account.user_name</code>.
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter for <code>public.account.birthday</code>.
     */
    public LocalDateTime getBirthday() {
        return this.birthday;
    }

    /**
     * Setter for <code>public.account.birthday</code>.
     */
    public void setBirthday(LocalDateTime birthday) {
        this.birthday = birthday;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(telegramId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(userName);
        sb.append(", ").append(birthday);

        sb.append(")");
        return sb.toString();
    }
}
