/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatDb implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    chatId;
    private String  title;
    private String  chatType;
    private Boolean holidayNotice;
    private Boolean birthdayNotice;
    private Boolean dailyNotice;

    public ChatDb() {}

    public ChatDb(ChatDb value) {
        this.chatId = value.chatId;
        this.title = value.title;
        this.chatType = value.chatType;
        this.holidayNotice = value.holidayNotice;
        this.birthdayNotice = value.birthdayNotice;
        this.dailyNotice = value.dailyNotice;
    }

    public ChatDb(
        Long    chatId,
        String  title,
        String  chatType,
        Boolean holidayNotice,
        Boolean birthdayNotice,
        Boolean dailyNotice
    ) {
        this.chatId = chatId;
        this.title = title;
        this.chatType = chatType;
        this.holidayNotice = holidayNotice;
        this.birthdayNotice = birthdayNotice;
        this.dailyNotice = dailyNotice;
    }

    /**
     * Getter for <code>public.chat_db.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.chat_db.chat_id</code>.
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.chat_db.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.chat_db.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.chat_db.chat_type</code>.
     */
    public String getChatType() {
        return this.chatType;
    }

    /**
     * Setter for <code>public.chat_db.chat_type</code>.
     */
    public void setChatType(String chatType) {
        this.chatType = chatType;
    }

    /**
     * Getter for <code>public.chat_db.holiday_notice</code>.
     */
    public Boolean getHolidayNotice() {
        return this.holidayNotice;
    }

    /**
     * Setter for <code>public.chat_db.holiday_notice</code>.
     */
    public void setHolidayNotice(Boolean holidayNotice) {
        this.holidayNotice = holidayNotice;
    }

    /**
     * Getter for <code>public.chat_db.birthday_notice</code>.
     */
    public Boolean getBirthdayNotice() {
        return this.birthdayNotice;
    }

    /**
     * Setter for <code>public.chat_db.birthday_notice</code>.
     */
    public void setBirthdayNotice(Boolean birthdayNotice) {
        this.birthdayNotice = birthdayNotice;
    }

    /**
     * Getter for <code>public.chat_db.daily_notice</code>.
     */
    public Boolean getDailyNotice() {
        return this.dailyNotice;
    }

    /**
     * Setter for <code>public.chat_db.daily_notice</code>.
     */
    public void setDailyNotice(Boolean dailyNotice) {
        this.dailyNotice = dailyNotice;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatDb (");

        sb.append(chatId);
        sb.append(", ").append(title);
        sb.append(", ").append(chatType);
        sb.append(", ").append(holidayNotice);
        sb.append(", ").append(birthdayNotice);
        sb.append(", ").append(dailyNotice);

        sb.append(")");
        return sb.toString();
    }
}
