/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Media implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private byte[] media;
    private String mediaType;
    private String mediaFormat;

    public Media() {}

    public Media(Media value) {
        this.id = value.id;
        this.media = value.media;
        this.mediaType = value.mediaType;
        this.mediaFormat = value.mediaFormat;
    }

    public Media(
        UUID   id,
        byte[] media,
        String mediaType,
        String mediaFormat
    ) {
        this.id = id;
        this.media = media;
        this.mediaType = mediaType;
        this.mediaFormat = mediaFormat;
    }

    /**
     * Getter for <code>public.media.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.media.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.media.media</code>.
     */
    public byte[] getMedia() {
        return this.media;
    }

    /**
     * Setter for <code>public.media.media</code>.
     */
    public void setMedia(byte[] media) {
        this.media = media;
    }

    /**
     * Getter for <code>public.media.media_type</code>.
     */
    public String getMediaType() {
        return this.mediaType;
    }

    /**
     * Setter for <code>public.media.media_type</code>.
     */
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * Getter for <code>public.media.media_format</code>.
     */
    public String getMediaFormat() {
        return this.mediaFormat;
    }

    /**
     * Setter for <code>public.media.media_format</code>.
     */
    public void setMediaFormat(String mediaFormat) {
        this.mediaFormat = mediaFormat;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Media (");

        sb.append(id);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(mediaType);
        sb.append(", ").append(mediaFormat);

        sb.append(")");
        return sb.toString();
    }
}
