/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Public;
import jooq.tables.records.ChatDbRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatDb extends TableImpl<ChatDbRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chat_db</code>
     */
    public static final ChatDb CHAT_DB = new ChatDb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChatDbRecord> getRecordType() {
        return ChatDbRecord.class;
    }

    /**
     * The column <code>public.chat_db.chat_id</code>.
     */
    public final TableField<ChatDbRecord, Long> CHAT_ID = createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chat_db.title</code>.
     */
    public final TableField<ChatDbRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.chat_db.chat_type</code>.
     */
    public final TableField<ChatDbRecord, String> CHAT_TYPE = createField(DSL.name("chat_type"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.chat_db.holiday_notice</code>.
     */
    public final TableField<ChatDbRecord, Boolean> HOLIDAY_NOTICE = createField(DSL.name("holiday_notice"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.chat_db.birthday_notice</code>.
     */
    public final TableField<ChatDbRecord, Boolean> BIRTHDAY_NOTICE = createField(DSL.name("birthday_notice"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.chat_db.daily_notice</code>.
     */
    public final TableField<ChatDbRecord, Boolean> DAILY_NOTICE = createField(DSL.name("daily_notice"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private ChatDb(Name alias, Table<ChatDbRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChatDb(Name alias, Table<ChatDbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.chat_db</code> table reference
     */
    public ChatDb(String alias) {
        this(DSL.name(alias), CHAT_DB);
    }

    /**
     * Create an aliased <code>public.chat_db</code> table reference
     */
    public ChatDb(Name alias) {
        this(alias, CHAT_DB);
    }

    /**
     * Create a <code>public.chat_db</code> table reference
     */
    public ChatDb() {
        this(DSL.name("chat_db"), null);
    }

    public <O extends Record> ChatDb(Table<O> child, ForeignKey<O, ChatDbRecord> key) {
        super(child, key, CHAT_DB);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ChatDbRecord> getPrimaryKey() {
        return Keys.CHAT_DB_PKEY;
    }

    @Override
    public ChatDb as(String alias) {
        return new ChatDb(DSL.name(alias), this);
    }

    @Override
    public ChatDb as(Name alias) {
        return new ChatDb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatDb rename(String name) {
        return new ChatDb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatDb rename(Name name) {
        return new ChatDb(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
