/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import jooq.Keys;
import jooq.Public;
import jooq.tables.records.MediaChatRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MediaChat extends TableImpl<MediaChatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.media_chat</code>
     */
    public static final MediaChat MEDIA_CHAT = new MediaChat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaChatRecord> getRecordType() {
        return MediaChatRecord.class;
    }

    /**
     * The column <code>public.media_chat.media_id</code>.
     */
    public final TableField<MediaChatRecord, UUID> MEDIA_ID = createField(DSL.name("media_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.media_chat.chat_id</code>.
     */
    public final TableField<MediaChatRecord, Long> CHAT_ID = createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.media_chat.expired_at</code>.
     */
    public final TableField<MediaChatRecord, LocalDate> EXPIRED_AT = createField(DSL.name("expired_at"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private MediaChat(Name alias, Table<MediaChatRecord> aliased) {
        this(alias, aliased, null);
    }

    private MediaChat(Name alias, Table<MediaChatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.media_chat</code> table reference
     */
    public MediaChat(String alias) {
        this(DSL.name(alias), MEDIA_CHAT);
    }

    /**
     * Create an aliased <code>public.media_chat</code> table reference
     */
    public MediaChat(Name alias) {
        this(alias, MEDIA_CHAT);
    }

    /**
     * Create a <code>public.media_chat</code> table reference
     */
    public MediaChat() {
        this(DSL.name("media_chat"), null);
    }

    public <O extends Record> MediaChat(Table<O> child, ForeignKey<O, MediaChatRecord> key) {
        super(child, key, MEDIA_CHAT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaChatRecord> getPrimaryKey() {
        return Keys.MEDIA_CHAT_PKEY;
    }

    @Override
    public List<ForeignKey<MediaChatRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_CHAT__FK_EXISTS_MEDIA, Keys.MEDIA_CHAT__FK_EXISTS_CHAT_DB);
    }

    private transient Media _media;
    private transient ChatDb _chatDb;

    /**
     * Get the implicit join path to the <code>public.media</code> table.
     */
    public Media media() {
        if (_media == null)
            _media = new Media(this, Keys.MEDIA_CHAT__FK_EXISTS_MEDIA);

        return _media;
    }

    /**
     * Get the implicit join path to the <code>public.chat_db</code> table.
     */
    public ChatDb chatDb() {
        if (_chatDb == null)
            _chatDb = new ChatDb(this, Keys.MEDIA_CHAT__FK_EXISTS_CHAT_DB);

        return _chatDb;
    }

    @Override
    public MediaChat as(String alias) {
        return new MediaChat(DSL.name(alias), this);
    }

    @Override
    public MediaChat as(Name alias) {
        return new MediaChat(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaChat rename(String name) {
        return new MediaChat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaChat rename(Name name) {
        return new MediaChat(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, Long, LocalDate> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
